### ISSUE TITLE
Create contract for storing mapping marketId -> list[ipfsHashes] for predictions

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#402] opened 2024-09-12 14:59 UTC
-> Create contract (maybe inherit from other contract or create a base class)
-> Write tests
-> Deploy to Gnosis chain

**Comment by kongzii** [comment] 2024-09-16 10:57
Duplicate of https://github.com/gnosis/prediction-market-agent-tooling/issues/363

**Closed** 2024-09-16 11:02 UTC
